### ISSUE TITLE
`gem install gollum` fails on Ruby 3.2 - error building rugged 1.1.1

### ISSUE THREAD

**Issue by firecat53** [gollum/gollum#1928]
**Describe the bug**
When installing gollum using `gem install --no-document gollum`, the install fails while attempting to build rugged 1.1.1 while using ruby 3.2. The build succeeds using ruby 3.1.

**To Reproduce**

    $ docker run -it --rm --entrypoint sh ruby:3.2alpine3.17
    # apk --no-cache add build-base \
                       cmake \
                       git \
                       icu-dev \
                       icu-libs \
                       openssl-dev
    # gem install --no-document gollum
    .....
    Building native extensions. This could take a while...
    ERROR:  Error installing gollum:
        ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/rugged-1.1.1/ext/rugged
    /usr/local/bin/ruby -I /usr/local/lib/ruby/3.2.0 extconf.rb
    checking for gmake... no
    checking for make... yes
    checking for cmake... yes
    checking for pkg-config... yes
    *** extconf.rb failed ***
    Could not create Makefile due to some reason, probably lack of necessary
    libraries and/or headers.  Check the mkmf.log file for more details.  You may 
    need configuration options.

    Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/bin/$(RUBY_BASE_NAME)
        --with-sha1dc
        --without-sha1dc
        --use-system-libraries
    extconf.rb:101:in `block in <main>': undefined method `exists?' for Dir:Class (NoMethodError)

    Dir.mkdir("build") if !Dir.exists?("build")
                              ^^^^^^^^
    Did you mean?  exist?
        from extconf.rb:100:in `chdir'
        from extconf.rb:100:in `<main>'

    To see why this extension failed to compile, please check the mkmf.log which can be found here:

      /usr/local/bundle/extensions/x86_64-linux-musl/3.2.0/rugged-1.1.1/mkmf.log

**Expected behavior**

Running the same sequence with: `ruby:3.1alpine3.17` completes correctly.

**Comment by dometto** [comment]
Thanks! Looks like a bug in `rugged` to me.

**Comment by svoop** [comment]
@dometto The dependency of `gollum-rugged_adapter` to `rugged ~> 1.1` is way out of date, current **rugged** installs fine on Ruby 3.2.

**Comment by svoop** [comment]
@dometto Poked around a little further and apparently, there are other dependencies which have to be fixed as well. I've stopped after two iterations of `File.exists?` present in dependencies (mustache-0.99.8 and gollum-lib-1.1.2 – already addressed in 6.x branch), but there might be more. Too deep a rabbit hole for now, time to prep for the party. 🥳 Happy New Year everybody!

**Comment by dometto** [comment]
See also https://github.com/mustache/mustache-sinatra/issues/10

**Comment by MadBomber** [comment]
Install still failing in Ruby 3.2 because dependencies have not been updated to latest version of rugged.

rugged v1.5.1 install just fine.

**Comment by shadyueh** [comment]
It seems the deps still pointing to 1.1.1
Is there a way to fix?
```
current directory: /home/<user>/.rvm/gems/ruby-3.2.1/gems/rugged-1.1.1/ext/rugged
/home/held/.rvm/rubies/ruby-3.2.1/bin/ruby -I /home/held/.rvm/rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0 extconf.rb
checking for gmake... yes
checking for cmake... yes
checking for pkg-config... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/held/.rvm/rubies/ruby-3.2.1/bin/$(RUBY_BASE_NAME)
	--with-sha1dc
	--without-sha1dc
	--use-system-libraries
extconf.rb:101:in `block in <main>': undefined method `exists?' for Dir:Class (NoMethodError)

    Dir.mkdir("build") if !Dir.exists?("build")
                              ^^^^^^^^
Did you mean?  exist?
	from extconf.rb:100:in `chdir'
	from extconf.rb:100:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/held/.rvm/gems/ruby-3.2.1/extensions/x86_64-linux/3.2.0/rugged-1.1.1/mkmf.log

extconf failed, exit code 1
```

**Comment by procraste** [comment]
Same thing here .... Any workaround ?

**Comment by dometto** [comment]
`mustache-sinatra` is currently blocking support for 3.2 (https://github.com/mustache/mustache-sinatra/issues/10). I've gotten in touch with the maintainer, but if they don't respond we may have to fork the library.

**Comment by dometto** [comment]
I've just released v5.3.1, which works with Ruby 3.2. The latest Docker image (`master`) is also now compatible.
