### ISSUE TITLE
How to enable AsciiDoc include:: in Gollum wiki?

### ISSUE THREAD

**Issue by saurabh-zz** [gollum/gollum#878]
It is my knowledge that the include:: macro was disabled due to security reasons in Gollum. We are planning to host the Gollum wiki internally. And as such there is no major concern regarding security. We would like to enable this feature as a lot of our earlier AsciiDoc documents use it. Can you point out where the modifications need to happen (am complete n00b to Ruby)?

Thanks.

**Comment by craibuc** [comment]
@saurabh, what did you need to do to enable asciidoctor's safe mode?

**Comment by saurabh** [comment]
@craibuc you need to search for markups.rb in github-markup gem; look for method call to Asciidoctor.render (this is the core rendering method which converts your markup to html). the 2nd parameter (:safe =>) you can change to any of the following:

A value of 0 (UNSAFE) disables any of the security features enforced by Asciidoctor (Ruby is still subject to its own restrictions).

A value of 1 (SAFE) closely parallels safe mode in AsciiDoc. In particular, it prevents access to files which reside outside of the parent directory of the source file and disables any macro other than the include macro.

A value of 10 (SERVER) disallows the document from setting attributes that would affect the conversion of the document, in addition to all the security features of SafeMode::SAFE. For instance, this value disallows changing the backend or the source-highlighter using an attribute defined in the source document. This is the most fundamental level of security for server-side deployments (hence the name).

A value of 20 (SECURE) disallows the document from attempting to read files from the file system and including the contents of them into the document, in addition to all the security features of SafeMode::SECURE. In particular, it disallows use of the include::[] macro and the embedding of binary content (data uri), stylesheets and JavaScripts referenced by the document. (Asciidoctor and trusted extensions may still be allowed to embed trusted content into the document).

**Comment by craibuc** [comment]
This modification, while easy enough to do, is less than ideal.  

While, I see that gollum-lib's `gemspec.rb` enforces a constraint on the github-markup gem (v.1.3.3), what happens if and when gollum-lib switches to a newer version of the github-markup gem?  I'll need to remember that I made this change to v1.3.3 and apply it to vMa.Mi.P.  Moreover, this setting affects all code that relies on this gem (admittedly few).

Ideally, there would be a wiki-specific setting that would alter this setting just for the wiki.

**Comment by dometto** [comment]
@craibuc, this being ruby, of course you don't need to edit any of `github-markup`'s source. Something like the following should work (untested) inside gollum's `config.rb`:

```ruby
require 'github/markup'
GitHub::Markup.markups.delete_if {|x| x.regexp == /asciidoc/}
base_url = 'http://localhost/wiki' # Your wiki's base url
GitHub::Markup.markup do |content|
 Asciidoctor.render(content, :safe => :safe, :attributes => %w(showtitle idprefix idseparator=- env=github env-github source-highlighter=html-pipeline))
end
```

**Comment by ellipticview** [comment]
The code above results in:
```
/var/lib/gems/2.1.0/gems/github-markup-1.3.3/lib/github/markup.rb:29:in `markup': wrong number of arguments (0 for 2..3) (ArgumentError)
        from /mnt/winbook/config.rb:4:in `<top (required)>'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /var/lib/gems/2.1.0/gems/gollum-4.0.0/bin/gollum:201:in `<top (required)>'
        from /usr/local/bin/gollum:23:in `load'
        from /usr/local/bin/gollum:23:in `<main>'
```
I'm afraid I don't have sufficient Ruby expertise to resolve.

**Comment by bartkamphorst** [comment]
@ellipticview The correct snippet is now [in the wiki](https://github.com/gollum/gollum/wiki/Formats-and-extensions#changing-github-markups-default-renderings-settings-eg-turning-asciidoctors-safe-mode-on).

**Comment by LeeWong** [comment]
I am facing the same issue cannot find the correct snippet in the above link. Please help.

**Comment by bartkamphorst** [comment]
The snippet was deleted from the above mentioned wiki page for reasons I don't know, so perhaps this no longer works, but here it is (found in the page's revisions btw).

```ruby
GitHub::Markup.markups.reject! {|markup| markup.regexp.to_s == '(?-mix:adoc|asc(iidoc)?)' }

GitHub::Markup.markup(:asciidoctor, /adoc|asc(iidoc)?/) do |content|
  Asciidoctor::Compliance.unique_id_start_index = 1
  Asciidoctor.convert(content, :safe => :safe, :attributes => %w(showtitle=@ idprefix idseparator=- env=github env-github source-highlighter=html-pipeline))
end
```

**Comment by LeeWong** [comment]
Thanks for the snippet you gave but it does not work with gollum v 4.1.4 . 
/wiki/config.rb:3:in `block in <top (required)>': undefined method `regexp' for :markdown:Symbol (NoMethodError)
	from /wiki/config.rb:3:in `reject!'
	from /wiki/config.rb:3:in `<top (required)>'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/local/bundle/gems/gollum-4.1.4/bin/gollum:251:in `<top (required)>'
	from /usr/local/bundle/bin/gollum:23:in `load'
	from /usr/local/bundle/bin/gollum:23:in `<main>'

What version you are using?

**Comment by bartkamphorst** [comment]
I'm on 5.0.1b, but as I said, I just dug up this snippet from the wiki, I haven't tested it.

**Comment by LeeWong** [comment]
Thanks for the timely reply. If you have time to test it, it will be great.  I don't know ruby very well. Thanks again.

**Comment by LeeWong** [comment]
I fixed the above snippet issue and here is the tested snippet:

```
GitHub::Markup.markups.reject! {|_name, markup| markup.regexp.to_s == '(?-mix:adoc|asc(iidoc)?)' }

GitHub::Markup.markup(:asciidoc, :asciidoctor, /adoc|asc(iidoc)?/, ["AsciiDoc"]) do |filename, content, options: {}|
  attributes = {
    'showtitle' => '@',
    'idprefix' => '',
    'idseparator' => '-',
    'sectanchors' => nil,
    'env' => 'github',
    'env-github' => '',
    'source-highlighter' => 'html-pipeline'
  }
  if filename
    attributes['docname']       = File.basename(filename, (extname = File.extname(filename)))
    attributes['docfilesuffix'] = attributes['outfilesuffix'] = extname
  else
    attributes['outfilesuffix'] = '.adoc'
  end
  Asciidoctor::Compliance.unique_id_start_index = 1
  Asciidoctor.convert(content, :safe => :safe, :attributes => attributes)
end
```
