### ISSUE TITLE
Test suite failures with rugged_adapter 0.4.3

### ISSUE THREAD

**Issue by adamniedzielski** [gollum/gollum#1187]
```
cat Gemfile.lock | grep rugged
```
```
    gollum-rugged_adapter (0.4.3)
      rugged (~> 0.24.0, >= 0.21.3)
    rugged (0.24.6.1)
  gollum-rugged_adapter (= 0.4.3)
```

```
bundle exec rake GIT_ADAPTER=rugged
```

```
/Users/adam/.rbenv/versions/2.3.3/bin/ruby -I"lib:lib:test:." -I"/Users/adam/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib" "/Users/adam/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "test/**/test_*.rb" 
Loaded suite /Users/adam/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/rake_test_loader
Started
....................................F
============================================================================================================================================================
Failure: test_urls_transform_unicode(Frontend)
/Users/adam/workspace/gollum/test/test_app.rb:38:in `block (2 levels) in <top (required)>'
<"m-plus-F"> expected but was
<"μ†ℱ">
============================================================================================================================================================
....E
============================================================================================================================================================
Error: test_transliteration(Frontend_Unicode_support): Rugged::InvalidError: Failed to parse signature - Signature cannot have an empty name or email
/Users/adam/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/gollum-rugged_adapter-0.4.3/lib/rugged_adapter/git_layer_rugged.rb:461:in `create'
/Users/adam/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/gollum-rugged_adapter-0.4.3/lib/rugged_adapter/git_layer_rugged.rb:461:in `commit'
/Users/adam/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/gollum-lib-4.2.2/lib/gollum-lib/committer.rb:170:in `commit'
/Users/adam/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/gollum-lib-4.2.2/lib/gollum-lib/wiki.rb:357:in `write_page'
/Users/adam/workspace/gollum/test/test_unicode.rb:94:in `block (2 levels) in <top (required)>'
============================================================================================================================================================
.............................

Finished in 5.866656 seconds.
------------------------------------------------------------------------------------------------------------------------------------------------------------
71 tests, 199 assertions, 1 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications
97.1831% passed
------------------------------------------------------------------------------------------------------------------------------------------------------------
12.10 tests/s, 33.92 assertions/s
rake aborted!
Command failed with status (1): [ruby -I"lib:lib:test:." -I"/Users/adam/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib" "/Users/adam/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/rake_test_loader.rb" "test/**/test_*.rb" ]
/Users/adam/.rbenv/versions/2.3.3/bin/bundle:22:in `load'
/Users/adam/.rbenv/versions/2.3.3/bin/bundle:22:in `<main>'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```

**Comment by adamniedzielski** [comment]
At first these two failures seem unrelated. However, when we take a look at `test_unicode.rb:94` we can see:

```
@wiki.write_page('ééééé'.to_url, :markdown, '한글 text', { :name => '', :email => '' })
```

That's the only place in the test suite where we pass an empty name and email. This is allowed by `grit`, but not allowed by `rugged`. The error comes deep down from `libgit2` - https://github.com/libgit2/libgit2/blob/8df1cfc9d710db48469e2ea34152cfe03d4bf515/src/signature.c#L88.

It's not super clear from the definition of `Gollum::Wiki#write_page` if `name` and `email` are required by `gollum-lib`. I assume that yes, but in https://github.com/gollum/gollum/blob/00dfecb1c7b7318651398c8b791ec95fe5065cb1/lib/gollum/app.rb#L576 we populate it from session only if it is provided, so there's a theoretical possibility that it would be empty.

If we agree that these two parameters are always required, we can change the test to:

```
@wiki.write_page('ééééé'.to_url, :markdown, '한글 text', commit_details)
```

We run the tests again and the error changes to:

```
Error: test_transliteration(Frontend_Unicode_support): NoMethodError: undefined method `raw_data' for nil:NilClass
```

That's because `@wiki.page('eeeee')` returns `nil`. If we change it to `@wiki.page('ééééé')` the test passes.

Hence, the real problem is that:
- `μ†ℱ` stays `μ†ℱ`
- `ééééé` stays `ééééé`

if we run the test suite against `rugged_adapter`. It is properly transliterated if we run the test suite against `grit_adapter`.

**Comment by adamniedzielski** [comment]
The problem is caused by https://github.com/gollum/gollum/commit/355db16d2c0c28116e4b0f50d9ee45536e394233.

The test suite has no chance to pass when `GIT_ADAPTER=rugged` is specified, because we have a different behavior for `rugged`.

@dometto I'm not sure what the best solution here is. Probably we should take this special case into account and modify the test suite so it expects different results depending on the value of `Gollum::GIT_ADAPTER`. What do you think?

**Comment by bartkamphorst** [comment]
Going forward it is probably best to write a test that can be satisfied by the rugged and rjgit adapters, as we are in the process of moving away from grit.
