### ISSUE TITLE
Ajax requests are not including the session cookie

### ISSUE THREAD

**Issue by exabrial** [gollum/gollum#927]
I added a wrapper around Gollum to authenticate requests using omniauth. This used to work just fine, but the livepreview page was updated at some point to make use of JQuery and AJAX.

When you click the save button now, rather than posting a form, the LivePreview now posts AJAX. `rack.session` is the name of the cookie that needs to be posted with the AJAX request, but for security reasons it's marked as HttpOnly. Somehow this is _not_ getting posted with the AJAX request, even though it should be automatically. 

This is usually caused by loading scripts across domains... but Gollum isn't doing that. So I'm not sure what't happening. This bug will break anything that uses Rack sessions.

**Comment by exabrial** [comment]
Read through the responses in http://stackoverflow.com/questions/2870371/why-is-jquerys-ajax-method-not-sending-my-session-cookie

The fix may be as simple as updating jquery.

**Comment by exabrial** [comment]
Ok, after clearing my cache and cookies, the request is now including the cookie, but the problem persists. Not sure what to do :( but I'll close this for now.

**Comment by dometto** [comment]
Updating jquery might not be a bad shot anyway, since gollum is still using a very old `v1.7.2`. I would be interested to hear whether updating it breaks anything, anyway. :)

**Comment by dometto** [comment]
@exabrial, as you may already be aware, there is also [omnigollum](https://github.com/arr2036/omnigollum), if that does what you want.

**Comment by exabrial** [comment]
Thanks guys, I'm looking into omnigollum. BTW, here is my config.ru for the app that I stole from somewhere else on github. I would then execute with "bundle exec puma" to start the app...

```ruby
#!/usr/bin/env ruby
require 'rubygems'
require 'gollum/app'
require 'omniauth'
require 'omniauth-ldap'

use Rack::Session::Cookie
use OmniAuth::Strategies::LDAP,{ 
  :title => "LDAP Login", 
  :host => 'ldap.corp.xxx.com',
  :port => 389,
  :method => :plain,
  :base => 'dc=corp,dc=xxx,dc=com',
  :filter => '(&(uid=%{username})(memberOf=cn=wiki_users,ou=groups,dc=corp,dc=xxx,dc=com))',
  :name_proc => Proc.new {|name| name.gsub(/@.*$/,'')},
  :bind_dn => 'cn=wiki,dc=corp,dc=xxx,dc=com',
  :password => 'random pasword'
  }

class OmniAuthSetGollumAuthor

  def initialize(app)
    @app = app
  end

  def call(env)
    request = Rack::Request.new(env)
    session = env['rack.session']

    # Check whether we are authorized, if not redirect.
    if request.path =~ /^\/(edit|create|revert|delete|livepreview)\// \
        and not session['gollum.author']
      session[:return_to] = request.fullpath
      # Redirect to authentication
      return [302, {'Location' => '/auth/ldap'}, []]
    end

    # Setting authentication information and redirect to previously intended location
    if request.path =~ /^\/auth\/[^\/]+\/callback/ and env['omniauth.auth']
      # puts env['omniauth.auth'].to_s
      # Creating the 'gollum.author' session object which indicates that
      # the request is authenticated.
      session['gollum.author'] = {
        :name => env['omniauth.auth'][:info][:displayName],
        :email => env['omniauth.auth'][:info][:email]
      }
      return_to = session[:return_to]
      puts 'Return to' + return_to
      session.delete(:return_to)
      return [302, {'Location' => return_to}, []]
    end
    @app.call(env)
  end
end

use OmniAuthSetGollumAuthor

Precious::App.set(:gollum_path, '/home/gollum/wiki')
Precious::App.set(:default_markup, :markdown)
Precious::App.set(:wiki_options, {:universal_toc => true, :allow_uploads => true, :mathjax => true, :show_all => true})
run Precious::App
```

**Comment by dometto** [comment]
@exabrial thanks for posting your config. What problem are you still experiencing, and what is the exact error message your getting?

**Comment by dometto** [comment]
Still need help with this? :)

**Comment by exabrial** [comment]
Yes! Sorry for the delayed response. To answer your question, the exact problem is the Session cookie is _not_ included in the AJAX requests coming from the Live Preview editor.

**Comment by dometto** [comment]
Are you sure the missing session is the problem? I just tried your config.ru and got a 'Forbidden' message, which I managed to fix by including `:allow_editing => true` among the `:wiki_options` hash.

**Comment by dometto** [comment]
I just tested only in the normal editor, but I can reproduce a problem with saving pages in the livepreview editor too when not explicitly setting `:allow_editing => true`. Give that a try?

**Comment by dometto** [comment]
Just released the fix for the `:allow_editing` issue in gollum `v3.1.2`. If that's your problem, you can consider it fixed. :) If not, please let me know.

**Comment by exabrial** [comment]
Argh... what platform are you on? I'm having trouble getting the latest version to even work on Ubuntu 14.04. 

Gemfile:
```ruby
source :rubygems
gem 'puma'
gem 'gollum'
gem 'omniauth'
gem 'omniauth-ldap'
```

StackTrace:
```
Puma caught this error: undefined method `join' for #<String:0x007f773c0b8578> (NoMethodError)
/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:37:in `rescue in call'
/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
/var/lib/gems/1.9.1/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
```

**Comment by exabrial** [comment]
That fixes it! Thank you
